import React from 'react';
import Header from '../Header'; // Assuming Header is in src/components/Header/index.js
import './index.css'; // Import About specific CSS

const About = () => {
  return (
    <>
      <Header /> {/* Render Header on the About page */}
      <div className="about-container">
        <h2 className="about-title">About GarudaTax AI</h2>
        <section className="about-section section-box">
          <h3>Our Mission</h3>
          <p>
            At GarudaTax AI, our mission is to revolutionize the way individuals approach tax filing in India. We believe that managing taxes should be simple, transparent, and stress-free. By leveraging cutting-edge Artificial Intelligence and Machine Learning, we empower users to navigate complex tax regulations with ease, ensuring accuracy and identifying optimal tax-saving opportunities.
          </p>
          <p>
            We are committed to providing a secure, efficient, and user-friendly platform that transforms tax compliance from a daunting annual task into a seamless, intelligent experience.
          </p>
        </section>

        <section className="about-section section-box">
          <h3>What We Offer</h3>
          <ul>
            <li>
              <strong>AI-Powered Document Processing:</strong> Upload various tax documents (Form 16, Form 26AS, bank statements, etc.), and our AI intelligently extracts relevant financial data, saving you hours of manual entry.
            </li>
            <li>
              <strong>Accurate Tax Computation:</strong> Our system applies the latest Indian tax laws (Old and New Regimes for FY 2023-24 / AY 2024-25) to precisely calculate your tax liability or refund.
            </li>
            <li>
              <strong>Personalized AI Suggestions:</strong> Receive tailored tax-saving recommendations generated by advanced AI models, helping you optimize your financial planning.
            </li>
            <li>
              <strong>ML-Driven Predictions:</strong> Get insights into your potential tax regime benefits and future tax liabilities based on predictive analytics.
            </li>
            <li>
              <strong>Comprehensive Tax History:</strong> Keep a digital record of all your past filings and computations, easily accessible for review and future reference.
            </li>
            <li>
              <strong>Interactive Tax Calculator:</strong> A manual tool to estimate your tax based on various income and deduction scenarios.
            </li>
            <li>
              <strong>Simplified ITR Form Generation:</strong> Generate a pre-filled ITR form based on your processed data, ready for review and submission.
            </li>
          </ul>
        </section>

        <section className="about-section section-box">
          <h3>Our Technology</h3>
          <p>
            GarudaTax AI is built on a robust and scalable architecture, utilizing:
          </p>
          <ul>
            <li>
              <strong>Flask & Python:</strong> For a powerful and flexible backend API.
            </li>
            <li>
              <strong>React.js:</strong> For a dynamic, responsive, and intuitive user interface.
            </li>
            <li>
              <strong>Google Gemini API:</strong> For state-of-the-art document understanding, data extraction, and intelligent text generation.
            </li>
            <li>
              <strong>Scikit-learn:</strong> For machine learning models that predict tax regimes and liabilities.
            </li>
            <li>
              <strong>MongoDB:</strong> For secure and efficient storage of user data and tax records.
            </li>
            <li>
              <strong>JWT Authentication:</strong> Ensuring secure user sessions and data protection.
            </li>
          </ul>
        </section>

        <section className="about-section section-box">
          <h3>Our Vision</h3>
          <p>
            We envision a future where tax filing is not a burden but an opportunity for financial growth. By continuously enhancing our AI capabilities and expanding our service offerings, GarudaTax AI aims to be the most trusted and comprehensive tax assistant for every Indian taxpayer.
          </p>
        </section>
      </div>
    </>
  );
};

export default About;
